name: fairness_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2023.12.12=h06a4308_0
  - expat=2.5.0=h6a678d5_0
  - libcxx=14.0.6=h83ecd13_0
  - libcxxabi=14.0.6=h06a4308_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libllvm11=11.1.0=h9e868ea_6
  - libstdcxx-ng=11.2.0=h1234567_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.0=h0371630_2
  - readline=7.0=h7b6447c_5
  - setuptools=68.2.2=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - backports-zoneinfo==0.2.1
      - cffi==1.16.0
      - clarabel==0.9.0
      - click==8.1.7
      - contourpy==1.1.1
      - cvxpy==1.5.2
      - cycler==0.12.1
      - ecos==2.0.14
      - fairsearchcore==1.0.4
      - filelock==3.16.1
      - flatbuffers==23.5.26
      - fonttools==4.55.3
      - fsspec==2024.10.0
      - gensim==4.3.2
      - importlib-metadata==7.0.1
      - importlib-resources==6.4.5
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.7
      - llvmlite==0.31.0
      - markupsafe==2.1.3
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - networkx==3.1
      - nltk==3.8.1
      - numba==0.48.0
      - numpy==1.23.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - osqp==0.6.7.post3
      - packaging==24.2
      - pandas==2.0.3
      - pillow==10.4.0
      - pycparser==2.21
      - pyparsing==3.1.4
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.2
      - qdldl==0.1.7.post4
      - rank-bm25==0.2.2
      - regex==2023.12.25
      - rpy2==3.5.7
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - scs==3.2.7
      - seaborn==0.13.2
      - six==1.16.0
      - smart-open==6.4.0
      - sympy==1.13.3
      - threadpoolctl==3.2.0
      - torch==2.4.1
      - tqdm==4.66.1
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2023.4
      - tzlocal==5.2
      - zipp==3.17.0
prefix: /home/crus/anaconda3/envs/fairness_env
